const nome = prompt("Digite seu nome");
document.body.innerHTML += `seu nome é <strong>${nome}</strong> <br />`;
document.body.innerHTML += `seu nome tem ${nome.length} letras <br />`
document.body.innerHTML += `a segunda letra do seu nome é ${nome[1]} <br />`
document.body.innerHTML += `primeiro indice da letra a é ${nome.search("a")} <br />`
document.body.innerHTML += `o ultimo indice da letra a é ${nome.toString().lastIndexOf("a")} <br />`
document.body.innerHTML += `as ultimas 3 letras do seu nome sao ${nome.slice(-3)} <br />`
document.body.innerHTML += `as palavras do seu nome são: ${nome.split(" ")} <br />`
document.body.innerHTML += `seu nome com letras maiusculas ${nome.toUpperCase()} <br />`
document.body.innerHTML += `seu nome com letras minusculas ${nome.toLowerCase()} <br />`
